- name: Install Kubernetes K3s cluster
  hosts: agents,servers
  become: yes
  vars:
    network_cidr: "192.168.1.0/24"
  roles:
    - role: firewall
      tags: firewall
    - role: k3
      tags: k3